### ISSUE TITLE
404 not found on navigation menu

### ISSUE THREAD

**Issue by do-web** [VirtusLab/strapi-plugin-navigation#16]
If i access the navigation menu in strapi i got:

GET http://localhost:1337/navigation/config 404 (Not Found)

**Comment by cyp3rius** [comment]
Hi @do-web, may I ask for some info about strapi version and plugin version you're usign? Screenshot of the console (network) will be also useful to let us investigate the problem.

**Comment by do-web** [comment]
Old 3.0 beta version sorry.

**Comment by cyp3rius** [comment]
No probs, after update it works I assume? :)
