### ISSUE TITLE
Related Content doesn't work

### ISSUE THREAD

**Issue by milanffm** [VirtusLab/strapi-plugin-navigation#20]
Hey, 
thanks for this plugin, I really need such one :-)

**Versions:**
"strapi": "3.3.3"
"strapi-plugin-navigation": "^1.0.0-beta.12"

**I create a github repro:**
[https://github.com/milanffm/strapi-navigation](https://github.com/milanffm/strapi-navigation)

I tried to add a Content Type to the navigationItems:

page-content.settings.json

`{
  "kind": "collectionType",
  "collectionName": "page_contents",
  "info": {
    "name": "PageContent",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "text": {
      "type": "richtext"
    },
    "image": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false
    },
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
  },
  "navigation": {
    "model": "navigationitem",
    "plugin": "navigation",
    "via": "related",
    "configurable": false,
    "hidden": true
  }
}
`

but I can't select this page_contents under "Releated" in navigationItem:

![Bildschirmfoto 2020-11-20 um 16 22 01](https://user-images.githubusercontent.com/16035756/99817001-a7f08a00-2b4c-11eb-80ea-e94555fe52b4.png)

**Comment by cyp3rius** [comment]
@milanffm as I see you've tried to manage everything via built-in Strapi Content Manager. Content Types delivered via plugin have to be managed by special UI also provided by plugin, otherwise we cannot guarantee data consistency. 

You can find it in the left menu "Plugins" -> "UI Navigation".

**Comment by WebDev-op** [comment]
And when created with  "Plugins" -> "UI Navigation" -  Related Content doesn't work to

**Comment by WebDev-op** [comment]
I found a solution to this issue here: https://github.com/VirtusLab/strapi-plugin-navigation#content-type-model-relation-to-navigation-item

To enable Content Type to work with Navigation Item, you've to add following field to your model *.settings.json:
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
inside the attributes section like in example below:
    "attributes": {
        ...,
        "navigation": {
            "model": "navigationitem",
            "plugin": "navigation",
            "via": "related",
            "configurable": false,
            "hidden": true
        },
        ...
    },

**Comment by WebDev-op** [comment]
And to be able to edit from navigationitem, it is necessary to disable / remove the "releted field" from the display settings in the "constructor-types": "NavigationItem.

**Comment by cyp3rius** [comment]
@WebDev-op when you remove „via: related” from the schema it might stop working / updating relations. Such construction follows the strapi docs.

**Comment by WebDev-op** [comment]
> @WebDev-op when you remove „via: related” from the schema it might stop working / updating relations. Such construction follows the strapi docs.
> 
> If indeed you just changed the display options, that not is not affecting the logic. But in that case if you are not using dedicated UI you’re loosing the deep validations and duplication control, so easy you might malform your data. Just making you aware :)

i have disabled from display in navigation-items. With this, I can go in and edit item in items. But all the necessary relationships, I freely edit in the ui navigation section. So far, I have not noticed any problems.

**Comment by cyp3rius** [comment]
We will make a test then :)
