### ISSUE TITLE
Can't register an internal link related to Single type

### ISSUE THREAD

**Issue by Norbz** [VirtusLab/strapi-plugin-navigation#23]
Hi there,

First of all, thanks for the work, it's an amazing plugin !

One drawback I see is the inability to create internal link toward a single type.

Typical use case is having a "homepage" single type that contains configuration or content about the homepage of your website. Right now, you can't add a menu item linked to a single type as it cannot list the entities.

A simple workaround would be to create an external link, but if I want to redirect to `/` for my react or vue frontend, then the external link regexp doesn't match.

<img width="706" alt="Capture d’écran 2021-01-05 à 16 21 34" src="https://user-images.githubusercontent.com/6388929/103664261-5e2ff780-4f72-11eb-8377-9fcfc85dd66d.png">

Do you think that could be upgradable ?

Thanks !

**Comment by cyp3rius** [comment]
Hi @Norbz, thanks for reporting to us.

Your request for support of Single Types sounds reasonable, and we will consider it for next beta release.

**Comment by Norbz** [comment]
Great news ! Thanks !

**Comment by cyp3rius** [comment]
@Norbz  version `1.0.0-beta.14 ` has been just released. Feature has been covered as part of it.

Confirm and close please.

**Comment by cyp3rius** [comment]
@Norbz  new version that contains wider support for Single Types has been released as `1.0.0-beta.17`. Test and close the ticket please.

**Comment by botmaster** [comment]
Hello Norbz.
I have to create internal link toward a single type in a menu system. Did you manage to do it ?
Thanks!
