### ISSUE TITLE
Content-Type Entity empty

### ISSUE THREAD

**Issue by TheManFromEarth1** [VirtusLab/strapi-plugin-navigation#26]
My setup:

1. Inside /config/server.js, I have included the plugins part with Pages Collection:

`module.exports = ({ env }) => ({
  host: env('HOST', 'localhost'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'xx'),
    },
  },
  plugins: {
      navigation: {
        additionalFields: ['audience'],
        excludedContentTypes: ["plugins::", "strapi"],
        allowedLevels: 2,
        contentTypesNameFields: {
          'Pages': ['Title'],
        },
      },
    },
});`

2. Then inside /api/pages/models/pages.settings.json
Under existing attributes, I have added the navigation object under existing attributes: 

`
  "attributes": {
    "Title": {
      "type": "string"
    },
    "collections": {
      "collection": "collection"
    },
    "Description": {
      "type": "richtext"
    },
    "navigation": {
            "model": "navigationitem",
            "plugin": "navigation",
            "via": "related",
            "configurable": false,
            "hidden": true
    }`

3. Now I'm able to run yarn develop --watch-admin without an error.

4. When I try to add an Navigation Item with relation to "Pages", the dropdown values of Entity are empty. 
Like I can see that there are several entries, but Title is empty so I don't know what I select.

Also various errors when I try to save. 

Questions:
a) Is my setup above from step 1 and 2 wrong?

**Comment by cyp3rius** [comment]
Hi @TheManFromEarth1,

based on documentation the part:

```"plugins":{
   "navigation":{
      "additionalFields":[
         "audience"
      ],
      "excludedContentTypes":[
         "plugins::",
         "strapi"
      ],
      "allowedLevels":2,
      "contentTypesNameFields":{
         "Pages":[
            "Title"
         ]
      }
   }
}```

have to be added to `config/custom.js` or `config/<env>/custom.js`. Plugin is pulling configuration from that location. See the [Readme.md](https://github.com/VirtusLab/strapi-plugin-navigation#configuration)

Same in point 2. you're adding it on a wrong level. See the [Readme.md](https://github.com/VirtusLab/strapi-plugin-navigation#content-type-model-relation-to-navigation-item) -> `inside the attributes section [...]`

Before raising the issue, please make sure you're following all the steps of setup & configuration.

**Comment by mhdaouas** [comment]
I still get an empty list even with the right config as you mentioned. What is the cause of the issue?

**Comment by cyp3rius** [comment]
@mhdaouas provide please your configuration file snippet. Without that it's just guessing.
