### ISSUE TITLE
Related entity not returned in response

### ISSUE THREAD

**Issue by gdulus** [VirtusLab/strapi-plugin-navigation#29]
First of all, thanks for a great plugin, it seems it has everything I need at this moment, but I hit some issue described below.

**ENV**:
StraAPI (official docker image): 3.4.6
MongoDB: 4.4.3

**Problem:** 
While calling navigation API 

```
http://localhost:1337/navigation/render/main-navigation
```

response is returned without related element:

```
[{:path "/",
  :_id "601c83066fffe1000e2f3519",
  :updatedAt "2021-02-04T23:28:06.154Z",
  :menuAttached false,
  :parent nil,
  :uiRouterKey "home-page",
  :createdAt "2021-02-04T23:28:06.147Z",
  :type "INTERNAL",
  :related [{:__contentType "Page"}],
  :title "Home page",
  :__v 0,
  :id "601c83066fffe1000e2f3519",
  :audience [],
  :order 1,
  :items nil,
  :master "601c749a98e86701000694bb"}]
```

Configuration of the Page model 

```
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "name": "Page",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "content": {
      "type": "dynamiczone",
      "components": [
        "content.single-column-text",
        "content.three-column-text",
        "content.two-column-text"
      ]
    },
    "pageMeta": {
      "type": "component",
      "repeatable": false,
      "component": "config.page-meta"
    },
    "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
  }
}
```

In GUI i can see that Page relation has been selected but there is no title like in documentation:

![image](https://user-images.githubusercontent.com/316217/106969571-5cad4700-674b-11eb-86e2-1ed83b4d84ad.png)

Plugin seems to recognize Page relation correctly as I can see the names in the configuration dropdown

![image](https://user-images.githubusercontent.com/316217/106970049-61bec600-674c-11eb-9589-247296b114d1.png)

**Comment by cyp3rius** [comment]
Thanks for report @gdulus, we've to test the plugin against `3.4.6` then, as with `3.4.5` all were working as expected.
