### ISSUE TITLE
Allowing entity to be selected multiple times

### ISSUE THREAD

**Issue by alexoesmith** [VirtusLab/strapi-plugin-navigation#360]
Is it possible to allow entities to be selected more than once. For example, adding the same category entity within another nested item? 

e.g.
New > Clothing > Jeans
Used > Clothing > Jeans

Clothing and jeans need to ideally be the same entity to save adding them multiple times.

Thanks.

**Comment by CodeVoyager** [comment]
Hi @alexoesmith 

Current one entity limit per navigation is a left-over from previous Strapi version. There was relation persistence issue when the same entity was used multiple navigation items.

There's a plan to remove this limitation in near future. At the moment I cannot say for sure when this will happen.

**Comment by AhmedRyad22** [comment]
any workaround for this one ? i have the same issue here
