### ISSUE TITLE
[strapi-plugin-navigation] - Submenu without relation

### ISSUE THREAD

**Issue by danestves** [VirtusLab/strapi-plugin-navigation#40]
![image](https://user-images.githubusercontent.com/31737273/109532412-7b270980-7a8f-11eb-9eef-d14068c69d58.png)

I want to create a submenu and make the first item empty because i only going to use the label, to work like this:

![image](https://user-images.githubusercontent.com/31737273/109532528-972aab00-7a8f-11eb-964d-7b75b4b95813.png)

The label and the submenu items they will have relations or external as a normal use. But until now there is not way to make a submenu without a relation or url, and sometimes there is not need to put it

**Comment by cyp3rius** [comment]
@danestves in upcoming version `beta.17` there will be ability to create external link to `#anchor`, for relations unfortunately it's against the concept we took so for version `1.0.0` we're not going to cover that. In the future, it's not said we won't :)

**Comment by cyp3rius** [comment]
@danestves  new version that contains above change has been released as `1.0.0-beta.17`
