### ISSUE TITLE
Clicking 'Save' a second time after adding a new menu item in the UI builder results in an error.

### ISSUE THREAD

**Issue by eugeneingram** [VirtusLab/strapi-plugin-navigation#42]
![image](https://user-images.githubusercontent.com/11439060/109870663-4c14c180-7c62-11eb-9a7a-1a711e1c258f.png)

**Comment by cyp3rius** [comment]
@eugeneingram new version that contains fix has been released as `1.0.0-beta.17`. Test an close the ticket please.

**Comment by eugeneingram** [comment]
Thanks, 1.0.0-beta.17 fixes the issue.
