### ISSUE TITLE
Navigation Items created through the UI builder seem incompatible with the NavigationItem content type editor and vice versa.

### ISSUE THREAD

**Issue by eugeneingram** [VirtusLab/strapi-plugin-navigation#43]
![image](https://user-images.githubusercontent.com/11439060/109870921-90a05d00-7c62-11eb-81be-952ba1e5201a.png)

items created directly as a NavigationItem content type error when attempting to edit in the UI builder:

![image](https://user-images.githubusercontent.com/11439060/109871086-b594d000-7c62-11eb-850f-e40123d8ff3e.png)

**Comment by cyp3rius** [comment]
@eugeneingram that expected because Strapi Content Builder is not supporting custom features required by those models.

We are supporting only issues raised against the Navigation UI created as part of the plugin.
