### ISSUE TITLE
Unable to change the Structure of a Type, after added to Navigation

### ISSUE THREAD

**Issue by jfahrni** [VirtusLab/strapi-plugin-navigation#47]
After adding the Configuration to use a Type as Relation in the Navigation, i am unable to make any changes in a Type (via Content-Types-Builder).

Steps to Reproduce:

- create new collection type (ex. Pages)
- add the Configuration for using in Navigation in the page.settings.json
```
  "navigation": {
      "model": "navigationitem",
      "plugin": "navigation",
      "via": "related",
      "configurable": false,
      "hidden": true
    }
```

- Go to Content-Type-Builder and to add another Field.
- Save => "an Error Occurred"

Console Output: debug PUT /content-type-builder/content-types/application::page.page (16 ms) 400

Error in Console: 
```
error:
   contentType.attributes.navigation.nature: Array(1)
       0: "must be one of the following values: oneWay, manyWay, oneToOne, oneToMany, manyToOne, manyToMany"
       length: 1
```

**Comment by cyp3rius** [comment]
@jfahrni and unfortunately such behavior is expected. Strapi built-in Content Builder is not supporting such advanced relations like polymorphic (that is the one). After creating a poly field via json schema you have to keep that method of editing. 

Maybe in the future Strapi will provide support for advanced relations.

**Comment by cyp3rius** [comment]
Closing as case can’t be addressed by us as plugin authors. Follow the json schema edit and all will work fine.

**Comment by tanc** [comment]
Just going to mention this here as it is not clear what "Follow the json schema edit" means unless you know Strapi quite well. To edit the schema you need to find the collection you want to edit the schema for in the `/api` directory in the Strapi folder. Say you are editing a collection called `pages` this would be in `/api/pages`. You then need to find and edit the file called `[collection-name].settings.json` under the `models` folder. In my example this would be at `/api/pages/models/pages.settings.json`

Edit that file and make the modifications you need. Then save and rebuild the UI with `yarn build`, or if using the docker images something like `docker-compose exec strapi yarn build` where `strapi` is your container name.

Hope this helps someone (or maybe me next time I search).
