### ISSUE TITLE
Error saving changes to content types that have been allocated to a navigation menu.

### ISSUE THREAD

**Issue by eugeneingram** [VirtusLab/strapi-plugin-navigation#52]
I have a content type 'Page' several items of which are allocated to a navigation menu.

If I attempt edit the 'Page' content type (I want to add a field).  It won't save.  I see this error in the response:

```{"error":{"contentType.attributes.navigation.nature":["must be one of the following values: oneWay, manyWay, oneToOne, oneToMany, manyToOne, manyToMany"]}}```

Are you able to look into this?

![image](https://user-images.githubusercontent.com/11439060/112305726-f2b71580-8c96-11eb-8ed3-d310d8a9b2c5.png)

**Comment by cyp3rius** [comment]
Hi @eugeneingram,

Issue you're referring to is a Strapi one, there is lack of support for Polymorphic relations in the Content Type Builder UI. I've answered the same in #47. You've to edit the type relevant json schema. That's not something we're able to solve, until Strapi core team does.

**Comment by eugeneingram** [comment]
Okay, thank you.  I was able to make the amendment via editing the JSON directly.
