### ISSUE TITLE
How to create a localized Navigation with strapi 3.6

### ISSUE THREAD

**Issue by prKrumm** [VirtusLab/strapi-plugin-navigation#59]
Any ideas how this plugin can be used with strapi 3.6 and its new i18n feature? 

If I want to associate a localized page with a navigation item I can pick only pages of the default locale.

**Comment by cyp3rius** [comment]
Good point @prKrumm we have got some ideas but first of all we want to collect your feedback and see which approach is the most accurate :)

Converting to discussion
