### ISSUE TITLE
Feature Request: expose Navigation and NavigationItem content-types as graphQL nodes

### ISSUE THREAD

**Issue by GatsbyGov** [VirtusLab/strapi-plugin-navigation#8]
As a developer, I would like Strapi-plugin-navigation to enhance it's compatibility with the Strapi GraphQL plugin and the 'gatsby-source-strapi' plugin for Gatsbyjs.

Configuration of 'gatsby-source-strapi' requires an array of Strapi content-types that Gatsby will use to infer it's GraphQL schema.

However, 'gatsby-source-strapi' is not currently compatible with the content-types managed by 'strapi-plugin-navigation' and a 404 error is returned by Gatsby during a build.

functionality includes:

- the addition of 'Find' action in the permission tab
- ability to query the tree structure return type using a graphql query
- expose the content types as root nodes in the graphql schema

![image](https://user-images.githubusercontent.com/66484547/97784847-55e5c580-1b99-11eb-84e2-259bd0b2e9ff.png)

**Comment by cyp3rius** [comment]
@GatsbyGov after deeper analysis seems that `gatsby-source-strapi` is not supporting strapi plugins and their content types as instead of `${apiURL}/${pluralize(contentType)}` the plugin content types are mostly accessible by `${apiURL}/${pluginName}/${pluginEndpoint}` by plugin exposed methods.

What I would like to manage is:

1. Prepare the `navigation/render` endpoint to deal with GQL or expose separated one, dedicated for this
2. Contribute to `gatsby-source-strapi` and add support for plugins and their controllers

**Comment by EAdeveloper** [comment]
![image](https://user-images.githubusercontent.com/21114220/101266729-d3b06a00-371f-11eb-9041-368733889cd1.png)

**Comment by EAdeveloper** [comment]
Hello @GatsbyGov and @cyp3rius,

I publised a "gatsby source plugin" to fetch and expose the Navigations as graphQL nodes in gatsby.
[gatsby-source-strapi-plugin-navigation](https://www.npmjs.com/package/gatsby-source-strapi-plugin-navigation)

**Comment by cyp3rius** [comment]
@EAdeveloper I'm going to update docs with reference to your Gatsby plugin. If you feel that nav plugin itself might be more lifted to work with GQL, I'll be more than happy if you contribute to it :)

**Comment by EAdeveloper** [comment]
@cyp3rius Yes, please add it to the docs.
I will continue to add more optimizations and documentation for more configuration options on the gatsby source plugin. I would like to also contribute on the strapi plugin navigation as well, hopefully @strapi will release the next internal API version to build plugins more consistently and compatible with strapi itself.

**Comment by cyp3rius** [comment]
Looking forward :)

**Comment by cyp3rius** [comment]
@GatsbyGov @EAdeveloper closing the ticket then.
